### ISSUE TITLE
do not use I'm Feeling Lucky search by default

### ISSUE THREAD

**Issue by bsdf** [arnemart/SafariKeywordSearchLegacy#14]
plugin updated automatically and it took me a long time to figure out wtf was happening.

**Comment by arnemart** [comment]
The "feeling lucky" search has been the default for as long the extension has existed, in all non-beta versions of Safari. I understand that this may be confusing for some users and will consider changing it in a future version if people complain about it, however almost none have done so this far.

**Comment by bsdf** [comment]
i think the issue is that with the release of safari 6, the search bar has been integrated with the address bar so, at least for me, the interaction was very confusing. i'll close the issue, but i think it's definitely something to keep in mind as more users upgrade to the new version of safari

**Comment by paradoll** [comment]
bsdf is spot on; with Safari 6 and merge of the address and search bar, it was confusing for me as well. It would be nice if the default could be changed instead of typing out 'g' for a google search page. The default 'I'm feeling lucky' search is becoming a tedious learning curve and the only drawback to this plugin. 

EDIT: Just realized I didn't have to change the code to change the default as I overlooked the Settings page. I've switched the Default and g search functions :)

**Comment by arnemart** [comment]
Yeah, I realize that the default probably should be changed. I'll do this in the next release.

**Comment by sjk** [comment]
> EDIT: Just realized I didn't have to change the code to change the default as I overlooked the Settings page. I've switched the Default and g search functions :)

I'm curious why SKS's predefined Default keyword is for Google's “I'm feeling lucky” search instead of a regular Google search, like SKS's predefined 'g' and Safari 6's new omnibar default.  Changing it to the latter would essentially make it redundant with Safari 6, while more like its omnibar in Safari 5 (unless Yahoo! or Bing is the default search engine).

I've removed Default in Safari 5 & 6, preferring the separate search field in the former and default omnibar behavior in the latter.

Btw, it's confusing that "<engine> search" light grey text is displayed in the omnibar popup when typing any SKS keywords but AFAIK there's no way for extensions to override that.

**Comment by arnemart** [comment]
Fixed in ab2629ad1b8c922a41e30578c9a301f1f89cf8c9. In addition, I have changed how the default search is set -- now any defined search engine can be set as the default with a single button.
